# Generated by Django 4.2.6 on 2023-10-24 14:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='noAvatar.png', null=True, upload_to=api.models.Profile.upload_to),
        ),
    ]
